### PR TITLE
Feature/es 5.x support

### PR DESCRIPTION
**Pull request by NorDroN**
I've tried to upgrade plugin for support ES 5.0.
I added unminified js-file (all.js) and modified this file. If it's right, you can create minified file and use its.

### CODE REVIEW

**Comment by khodeprasad** [comment]
@NorDroN thanks for this update, this one is working fine. One issue that I see is while I submit a default query using **Query** feature I'm getting 
`{error: {root_cause: [{type: "parsing_exception",…}], type: "parsing_exception",…}, status: 400}`

My input is something like below:

Request URL:http://xxx.xx.xx.xxx:9200/index_name/_search

Form Data:
{"from":0,"size":50,"sort":{"_score":{"order":"asc"}},"fields":["field-1","field-2","field-3" ... ,"field-n",],"explain":true}

**Comment by mitchpenrod** [comment]
Hi Andrey, I'm currently taking over maintenance on ElasticHQ and working on ES 5.0 compatibility.

Just looking over your changes, the logic looks okay, but the structure has some issues. The all.js file you added is unnecessary--the all.min.js is generated by grunt (see DEVELOPMENT.md for more info). The actual changes go into the individual JS files (e.g. js/model/node/NodeModelFactory.js)

Could you please:
- Create a new Pull Request with your changes to the individual JS files
- Without all.js
- With all.min.js compiled using grunt dist
- Against the feature/ES_5.x_support branch I just created

I would greatly appreciate it. If you have any questions, please let me know. I'd be happy to do these changes myself, if you do not want to make them, however I wanted to give you the opportunity to get credit for the Pull Request.

Either way, please let me know how you'd like to proceed.

Thank you,
Mitch

**Comment by bluepuma77** [comment]
Is there a simple way to get the ES5 compatible version up and running?

**Comment by mrp14** [comment]
FYI, after applying @NorDroN branch diffs, almost everything seems to be working fine, except querying.

Here is the JSON response from ES  : 

```json
{"error":{"root_cause":[{"type":"parsing_exception","reason":"The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored","line":1,"col":64}],"type":"parsing_exception","reason":"The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored","line":1,"col":64},"status":400}
```

**Comment by NorDroN** [comment]
Hi, @mitchpenrod !
I'm really sorry, earlier I worked on a project which is associated with ES, I had to migrate our project on ES-5, but now I work on another project and I doesn't have enough time for this issue. I wanted to help you and gave my solution. You can do this changes himself. 
I simply want to make the world better! :)

**Comment by dinnyosz** [comment]
Hi @mitchpenrod,
do you may have any estimate on when will ES5 support merged to the master?

**Comment by mitchpenrod** [comment]
Closing as this was addressed in #277

**Pull request closed without merging**
